### ISSUE TITLE
CA null pointer exception

### ISSUE THREAD

**Issue by jinjingfarm** [InterPSS-Project/ipss20#23]
When performing CA, I got a null pointer exception. This happens for both single outage and multiple outage. Ref bus selected Bus-14.

![image](https://f.cloud.github.com/assets/5182378/1034885/3064bffa-0f21-11e3-9b2f-16d8d9ad7073.png)

**Comment by IpssDev** [comment]
After adding some code to print out the stack trace, it is easier to find out the cause. It is caused by the commit https://github.com/interpss/core/commit/a0d05466db4e9cec3c982070efe064a2248240cb setting lodf factor to be null fro multi-CA. However, this exception can be avoid by not adding the outage branches to the monitoring branch list. No core code changes are needed.

Instance key: 00c61b117c28cdcc9c7abf2c56c518f1443791f5
Date: Tue Aug 27 22:03:50 UTC 2013
Log: 
Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: com.interpss.pssl.util.ContingencyAnalysisHelper.multiOutageMonitorBranchFlow(ContingencyAnalysisHelper.java:363)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: com.interpss.pssl.util.ContingencyAnalysisHelper.contAnalysis(ContingencyAnalysisHelper.java:229)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: com.interpss.pssl.util.ContingencyAnalysisHelper.contAnalysis(ContingencyAnalysisHelper.java:134)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: com.interpss.service.impl.AlgorithmHelper.runCA(AlgorithmHelper.java:471)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: com.interpss.service.impl.AlgorithmHelper.runContingencyAnalysis(AlgorithmHelper.java:441)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: com.interpss.service.AlgorithmServiceServlet.serviceImpl(AlgorithmServiceServlet.java:92)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: com.interpss.service.AlgorithmServiceServlet.doPost(AlgorithmServiceServlet.java:39)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: javax.servlet.http.HttpServlet.service(HttpServlet.java:637)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: javax.servlet.http.HttpServlet.service(HttpServlet.java:717)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:35)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:266)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: org.mortbay.jetty.Server.handle(Server.java:326)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:439)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:435)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:442)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: com.google.tracing.CurrentContext.runInContext(CurrentContext.java:186)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:306)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:298)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:439)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:251)

Level: ERROR
Message: com.interpss.service.AlgorithmServiceServlet serviceImpl: java.lang.Thread.run(Thread.java:722)

Please contact support@interpss.com

**Comment by jinjingfarm** [comment]
Please see the update to https://github.com/interpss/core/issues/1.

**Comment by jinjingfarm** [comment]
Please see commit

https://github.com/interpss/core/commit/e22bd21e221637ef43c4ad3457a9708a91a3afda

**Comment by jinjingfarm** [comment]
Issue resolved with V2.2.1 build-2
