### ISSUE TITLE
Service exception reporting issue

### ISSUE THREAD

**Issue by jinjingfarm** [InterPSS-Project/ipss20#36]
When there is a service exception, clicking the Refresh button will result in another pop-up window:

![image](https://f.cloud.github.com/assets/5182378/1109727/3fa32a64-1986-11e3-9f0a-489f522a1460.png)

**Comment by IpssDev** [comment]
This issue is a known issue. The button_refreshHandlerFunction is in the shared library. However, sometimes App Script will look for it from the local script attached to the spreadsheet. This issue happens randomly. One way to solve this issue is to create a local pseudo version of all handler functions and then point to the real handler functions in the shared library.

**Comment by jinjingfarm** [comment]
Let us wait and see how serious is the issue, and then decide how to move forward.
